### ISSUE TITLE
Modify Elastic benchmark to run with OSB

### ISSUE THREAD

**Issue by gkamat** [opensearch-project/opensearch-benchmark-workloads#136]
The [benchmark recently published by Elastic](https://github.com/elastic/elasticsearch-opensearch-benchmark) requires a modified version of Rally to run.  Modifying it so that OSB can be used will be convenient for developers of open-source OpenSearch.

### Tasks
- [x] Customize published benchmark with OSB-compliant mappings
- [x] Generate associated data corpora files using the generator tool
- [x] Convert corpora files into unified corpus with offset file
- [x] Generate a packaged version of benchmark as POC
- [x] #162 
- [x] #163 
- [x] #164
